using System;


public class NegativoException : Exception {
	
	public NegativoException() {}
	
	public NegativoException(string message) : base(message) {}
	
	public NegativoException(string message, Exception  inner)
		: base(message, inner) {}
}
public class ImparException : Exception {
	public ImparException(string message) : base(message) {}
}
					
class ExcecoesPersonalizadas
{
	public static int PositivoPar() {
		Random random = new Random();
		int valor = random.Next(-30,30);
		
		if(valor < 0) {	
			throw new NegativoException("Numero Negativo ...");
			
			throw new ImparException("Valor Impar ...");
		} return valor;
	}
	public static void Main()
	{
		try {
			Console.WriteLine(PositivoPar());		
		} catch(NegativoException ex) {
			Console.WriteLine(ex.Message);
		} catch(ImparException ex) {
			Console.WriteLine(ex.Message);
		}
	}
}
